import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { addIcons } from 'ionicons';
import {
  arrowBackOutline,
  checkmarkOutline,
  warningOutline,
  mailOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  arrowForwardOutline,
  personOutline,
  callOutline,
  logoGoogle,
  closeOutline,
  checkmarkCircleOutline,
  alertCircleOutline,
  homeOutline,
  calendarOutline,
  addOutline,
  statsChartOutline,
  settingsOutline,
  notificationsOutline,
  trashOutline,
  createOutline,
  ellipsisVertical,
  chevronForwardOutline,
  chevronBackOutline,
  searchOutline,
  filterOutline,
  starOutline,
  star,
  heartOutline,
  timeOutline,
  flagOutline,
  checkmarkDoneOutline,
} from 'ionicons/icons';

addIcons({
  'arrow-back-outline': arrowBackOutline,
  'checkmark-outline': checkmarkOutline,
  'warning-outline': warningOutline,
  'mail-outline': mailOutline,
  'lock-closed-outline': lockClosedOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'person-outline': personOutline,
  'call-outline': callOutline,
  'logo-google': logoGoogle,
  'close-outline': closeOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'alert-circle-outline': alertCircleOutline,
  'home-outline': homeOutline,
  'calendar-outline': calendarOutline,
  'add-outline': addOutline,
  'stats-chart-outline': statsChartOutline,
  'settings-outline': settingsOutline,
  'notifications-outline': notificationsOutline,
  'trash-outline': trashOutline,
  'create-outline': createOutline,
  'ellipsis-vertical': ellipsisVertical,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-back-outline': chevronBackOutline,
  'search-outline': searchOutline,
  'filter-outline': filterOutline,
  'star-outline': starOutline,
  'star': star,
  'heart-outline': heartOutline,
  'time-outline': timeOutline,
  'flag-outline': flagOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
});

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
